# Generated by Django 4.0.6 on 2022-07-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='destinaton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(default='null', max_length=200)),
                ('c_id', models.IntegerField(default='null')),
                ('d_type', models.CharField(default='null', max_length=50)),
                ('d_image', models.CharField(default='null', max_length=500)),
            ],
        ),
    ]
