# Generated by Django 4.0.6 on 2022-07-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(default='null', max_length=200)),
                ('g_image', models.CharField(default='null', max_length=500)),
                ('g_type', models.CharField(default='null', max_length=100)),
                ('g_place', models.IntegerField(default='null')),
                ('g_place_type', models.CharField(default='null', max_length=10)),
                ('g_salary', models.IntegerField(default='null')),
                ('g_experience', models.CharField(default='null', max_length=100)),
                ('g_achivment', models.CharField(default='null', max_length=500)),
                ('g_about', models.CharField(default='null', max_length=5000)),
            ],
        ),
    ]
