# Generated by Django 4.0.6 on 2022-08-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_guide'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(default='null', max_length=500)),
                ('h_image', models.CharField(default='null', max_length=1000)),
                ('h_rate', models.IntegerField(default='null')),
                ('h_location', models.CharField(default='null', max_length=500)),
                ('h_room', models.CharField(default='null', max_length=1000)),
                ('h_room_about', models.CharField(default='null', max_length=500)),
                ('h_price', models.IntegerField(default='null')),
                ('h_place', models.IntegerField(default='null')),
                ('h_place_type', models.CharField(default='null', max_length=50)),
            ],
        ),
    ]
