# Generated by Django 4.0.6 on 2022-08-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='null', max_length=100)),
                ('user_phone_no', models.IntegerField(default='null')),
                ('user_password', models.CharField(default='null', max_length=50)),
            ],
        ),
    ]
