# Generated by Django 4.0.6 on 2022-08-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(default='null', max_length=100)),
                ('u_phone', models.IntegerField(default='null')),
                ('u_c_id', models.IntegerField(default='null')),
                ('u_h_name', models.CharField(default='null', max_length=500)),
                ('u_h_image', models.CharField(default='null', max_length=1000)),
                ('u_g_name', models.CharField(default='null', max_length=200)),
                ('u_main_destination', models.CharField(default='null', max_length=50)),
                ('u_sub_destination', models.CharField(default='null', max_length=50)),
            ],
        ),
    ]
